// <auto-generated />
using System;
using DDMdiplom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DDMdiplom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529134839_UpdateApplicationUser")]
    partial class UpdateApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BuildId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DDMdiplom.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DDMdiplom.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("DDMdiplom.Models.BuildItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ModuleCount")
                        .HasColumnType("integer");

                    b.Property<string>("StorageInterface")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("BuildItems");
                });

            modelBuilder.Entity("DDMdiplom.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaseMaterial")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<int?>("ExpansionSlots")
                        .HasColumnType("integer");

                    b.Property<string>("FanOptions")
                        .HasColumnType("text");

                    b.Property<string>("FrontPorts")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Internal25Bays")
                        .HasColumnType("text");

                    b.Property<string>("Internal35Bays")
                        .HasColumnType("text");

                    b.Property<string>("LED")
                        .HasColumnType("text");

                    b.Property<int?>("MaxCpuCoolerHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxGpuLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPsuLength")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotherboardCompatibility")
                        .HasColumnType("text");

                    b.Property<string>("PackageContent")
                        .HasColumnType("text");

                    b.Property<string>("PreInstalledFans")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RadiatorOptions")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("SidePanel")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("VerticalGpuSupport")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("DDMdiplom.Models.CpuCooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirFlow")
                        .HasColumnType("text");

                    b.Property<string>("BearingType")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("CpuSocketCompatibility")
                        .HasColumnType("text");

                    b.Property<string>("FanDimensions")
                        .HasColumnType("text");

                    b.Property<string>("FanMountingTypesToHeatsink")
                        .HasColumnType("text");

                    b.Property<string>("FanSize")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("HeatsinkDimensions")
                        .HasColumnType("text");

                    b.Property<string>("HeatsinkMaterial")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("MaxCpuCoolerHeight")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoiseLevel")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("Rpm")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CpuCoolers");
                });

            modelBuilder.Entity("DDMdiplom.Models.GraphicsCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoostClock")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardDimensions")
                        .HasColumnType("text");

                    b.Property<string>("ChipsetManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Cooler")
                        .HasColumnType("text");

                    b.Property<int?>("CoreClock")
                        .HasColumnType("integer");

                    b.Property<int?>("CudaCores")
                        .HasColumnType("integer");

                    b.Property<string>("DirectX")
                        .HasColumnType("text");

                    b.Property<int?>("DisplayPorts")
                        .HasColumnType("integer");

                    b.Property<int?>("EffectiveMemoryClock")
                        .HasColumnType("integer");

                    b.Property<string>("FormFactor")
                        .HasColumnType("text");

                    b.Property<string>("Gpu")
                        .HasColumnType("text");

                    b.Property<string>("GpuSeries")
                        .HasColumnType("text");

                    b.Property<string>("HdcpReady")
                        .HasColumnType("text");

                    b.Property<int?>("HdmiPorts")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Interface")
                        .HasColumnType("text");

                    b.Property<int?>("MaxGpuLength")
                        .HasColumnType("integer");

                    b.Property<string>("MaxResolution")
                        .HasColumnType("text");

                    b.Property<int?>("MemoryInterface")
                        .HasColumnType("integer");

                    b.Property<int?>("MemorySize")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MultiMonitorSupport")
                        .HasColumnType("integer");

                    b.Property<string>("OpenGL")
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<string>("PowerConnector")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RecommendedPsuWattage")
                        .HasColumnType("integer");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("SliSupport")
                        .HasColumnType("text");

                    b.Property<int?>("StreamProcessors")
                        .HasColumnType("integer");

                    b.Property<int?>("ThermalDesignPower")
                        .HasColumnType("integer");

                    b.Property<string>("VirtualRealityReady")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GraphicsCards");
                });

            modelBuilder.Entity("DDMdiplom.Models.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionType")
                        .HasColumnType("text");

                    b.Property<string>("DesignStyle")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<int?>("FunctionKeysCount")
                        .HasColumnType("integer");

                    b.Property<string>("HandOrientation")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsMechanical")
                        .HasColumnType("boolean");

                    b.Property<string>("KeySwitch")
                        .HasColumnType("text");

                    b.Property<string>("KeySwitchType")
                        .HasColumnType("text");

                    b.Property<string>("KeyboardColor")
                        .HasColumnType("text");

                    b.Property<string>("KeyboardInterface")
                        .HasColumnType("text");

                    b.Property<string>("Layout")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int?>("MouseButtons")
                        .HasColumnType("integer");

                    b.Property<string>("MouseIncluded")
                        .HasColumnType("text");

                    b.Property<string>("MouseInterface")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PowerSource")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("SystemRequirement")
                        .HasColumnType("text");

                    b.Property<string>("TrackingMethod")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Keyboards");
                });

            modelBuilder.Entity("DDMdiplom.Models.Memory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BiosProfiles")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Capacity")
                        .HasColumnType("text");

                    b.Property<string>("CasLatency")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("HeatSpreader")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LedColor")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModuleCount")
                        .HasColumnType("integer");

                    b.Property<string>("MultiChannelKit")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecommendUse")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("Speed")
                        .HasColumnType("text");

                    b.Property<string>("Timing")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<decimal?>("Voltage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Memory");
                });

            modelBuilder.Entity("DDMdiplom.Models.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdaptiveSyncTechnology")
                        .HasColumnType("text");

                    b.Property<string>("AspectRatio")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BrightnessHdr")
                        .HasColumnType("integer");

                    b.Property<int?>("BrightnessSdr")
                        .HasColumnType("integer");

                    b.Property<string>("BuiltInSpeakers")
                        .HasColumnType("text");

                    b.Property<string>("BuiltInWebcam")
                        .HasColumnType("text");

                    b.Property<string>("CabinetColor")
                        .HasColumnType("text");

                    b.Property<string>("ColorGamut")
                        .HasColumnType("text");

                    b.Property<string>("ContrastRatio")
                        .HasColumnType("text");

                    b.Property<string>("CurvedSurfaceScreen")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayColors")
                        .HasColumnType("text");

                    b.Property<string>("DisplayPort")
                        .HasColumnType("text");

                    b.Property<string>("DisplayType")
                        .HasColumnType("text");

                    b.Property<string>("HdcpSupport")
                        .HasColumnType("text");

                    b.Property<string>("HdmiPorts")
                        .HasColumnType("text");

                    b.Property<string>("HdrStandard")
                        .HasColumnType("text");

                    b.Property<string>("Headphone")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MaximumResolution")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonitorPixelDensity")
                        .HasColumnType("text");

                    b.Property<string>("MonitorType")
                        .HasColumnType("text");

                    b.Property<string>("Panel")
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<string>("PowerSupply")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RefreshRate")
                        .HasColumnType("integer");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("ResponseTime")
                        .HasColumnType("text");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("text");

                    b.Property<string>("StandAdjustments")
                        .HasColumnType("text");

                    b.Property<string>("ThreeDReady")
                        .HasColumnType("text");

                    b.Property<string>("VesaCompatibility")
                        .HasColumnType("text");

                    b.Property<string>("VideoPorts")
                        .HasColumnType("text");

                    b.Property<string>("ViewingAngle")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("DDMdiplom.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioChannels")
                        .HasColumnType("text");

                    b.Property<string>("AudioChipset")
                        .HasColumnType("text");

                    b.Property<string>("BiosFeature")
                        .HasColumnType("text");

                    b.Property<string>("Bluetooth")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Chipset")
                        .HasColumnType("text");

                    b.Property<string>("CpuSocketType")
                        .HasColumnType("text");

                    b.Property<string>("CpuType")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<string>("EccSupported")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("FormFactor")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InternalIoConnectors")
                        .HasColumnType("text");

                    b.Property<string>("LanChipset")
                        .HasColumnType("text");

                    b.Property<string>("LedLighting")
                        .HasColumnType("text");

                    b.Property<string>("M2Slots")
                        .HasColumnType("text");

                    b.Property<string>("MaxLanSpeed")
                        .HasColumnType("text");

                    b.Property<int?>("MaxMemorySize")
                        .HasColumnType("integer");

                    b.Property<int?>("MemorySlots")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryStandard")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PciExpress50x16")
                        .HasColumnType("text");

                    b.Property<string>("PciExpressX1")
                        .HasColumnType("text");

                    b.Property<string>("PciExpressX4")
                        .HasColumnType("text");

                    b.Property<string>("PowerConnectors")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RearPanelPorts")
                        .HasColumnType("text");

                    b.Property<string>("SataPorts")
                        .HasColumnType("text");

                    b.Property<string>("Software")
                        .HasColumnType("text");

                    b.Property<string>("WirelessLan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("DDMdiplom.Models.Mouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustableWeight")
                        .HasColumnType("text");

                    b.Property<string>("BatteryLife")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ButtonsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionType")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("GripStyle")
                        .HasColumnType("text");

                    b.Property<string>("HandOrientation")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Interface")
                        .HasColumnType("text");

                    b.Property<string>("Lighting")
                        .HasColumnType("text");

                    b.Property<int?>("MaxDpi")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageContents")
                        .HasColumnType("text");

                    b.Property<string>("PowerSource")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScrollingCapability")
                        .HasColumnType("text");

                    b.Property<string>("SupportedOperatingSystems")
                        .HasColumnType("text");

                    b.Property<string>("SystemRequirement")
                        .HasColumnType("text");

                    b.Property<string>("TrackingMethod")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<string>("WirelessRange")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mice");
                });

            modelBuilder.Entity("DDMdiplom.Models.OperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BitVersion")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disclaimer")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystems")
                        .HasColumnType("text");

                    b.Property<string>("Packaging")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SystemRequirements")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");
                });

            modelBuilder.Entity("DDMdiplom.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DDMdiplom.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuildId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DDMdiplom.Models.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Connectors")
                        .HasColumnType("text");

                    b.Property<string>("EnergyEfficient")
                        .HasColumnType("text");

                    b.Property<string>("Fans")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InputCurrent")
                        .HasColumnType("text");

                    b.Property<string>("InputFrequencyRange")
                        .HasColumnType("text");

                    b.Property<string>("InputVoltage")
                        .HasColumnType("text");

                    b.Property<string>("MainConnector")
                        .HasColumnType("text");

                    b.Property<int?>("MaxPsuLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximumPower")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modular")
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PowerSupplies");
                });

            modelBuilder.Entity("DDMdiplom.Models.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvancedTechnologies")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompatibleChipsets")
                        .HasColumnType("text");

                    b.Property<string>("CoolingDevice")
                        .HasColumnType("text");

                    b.Property<string>("CoreName")
                        .HasColumnType("text");

                    b.Property<int?>("Cores")
                        .HasColumnType("integer");

                    b.Property<string>("CpuSocketType")
                        .HasColumnType("text");

                    b.Property<int?>("GraphicsBaseFrequency")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstructionSet")
                        .HasColumnType("text");

                    b.Property<string>("IntegratedGraphics")
                        .HasColumnType("text");

                    b.Property<string>("L1Cache")
                        .HasColumnType("text");

                    b.Property<string>("L2Cache")
                        .HasColumnType("text");

                    b.Property<string>("L3Cache")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturingTech")
                        .HasColumnType("text");

                    b.Property<string>("MaxMemorySize")
                        .HasColumnType("text");

                    b.Property<string>("MaxPciExpressLanes")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxTurboFrequency")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("MemoryChannel")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryTypes")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("OperatingFrequency")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PciExpressRevision")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProcessorsType")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("SupportedOperatingSystems")
                        .HasColumnType("text");

                    b.Property<int?>("ThermalDesignPower")
                        .HasColumnType("integer");

                    b.Property<int?>("Threads")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Processors");
                });

            modelBuilder.Entity("DDMdiplom.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Cache")
                        .HasColumnType("integer");

                    b.Property<string>("Capacity")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("FormFactor")
                        .HasColumnType("text");

                    b.Property<string>("HeatSink")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Interface")
                        .HasColumnType("text");

                    b.Property<int?>("MaxSequentialRead")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSequentialWrite")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<string>("RecordingTechnology")
                        .HasColumnType("text");

                    b.Property<int?>("Rpm")
                        .HasColumnType("integer");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("Usage")
                        .HasColumnType("text");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("DDMdiplom.Models.Ups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alarms")
                        .HasColumnType("text");

                    b.Property<string>("Approvals")
                        .HasColumnType("text");

                    b.Property<int?>("BatteryRechargeTime")
                        .HasColumnType("integer");

                    b.Property<string>("BatteryReplaceable")
                        .HasColumnType("text");

                    b.Property<string>("BatteryRunTimeFullLoad")
                        .HasColumnType("text");

                    b.Property<string>("BatteryRunTimeHalfLoad")
                        .HasColumnType("text");

                    b.Property<string>("BatteryType")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataLineProtection")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InputConnection")
                        .HasColumnType("text");

                    b.Property<string>("InputFrequency")
                        .HasColumnType("text");

                    b.Property<string>("InputVoltageRange")
                        .HasColumnType("text");

                    b.Property<string>("InterfacePort")
                        .HasColumnType("text");

                    b.Property<string>("InternationalVersion")
                        .HasColumnType("text");

                    b.Property<string>("ManagementSoftware")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletType")
                        .HasColumnType("text");

                    b.Property<int?>("Outlets")
                        .HasColumnType("integer");

                    b.Property<string>("OutputFrequency")
                        .HasColumnType("text");

                    b.Property<string>("OutputVoltage")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Protection")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<int?>("SurgeEnergyRating")
                        .HasColumnType("integer");

                    b.Property<int?>("VaRating")
                        .HasColumnType("integer");

                    b.Property<int?>("Watts")
                        .HasColumnType("integer");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UpsDevices");
                });

            modelBuilder.Entity("DDMdiplom.Models.WaterCooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BearingType")
                        .HasColumnType("text");

                    b.Property<string>("BlockCompatibility")
                        .HasColumnType("text");

                    b.Property<string>("BlockCompatibilityAmd")
                        .HasColumnType("text");

                    b.Property<string>("BlockCompatibilityIntel")
                        .HasColumnType("text");

                    b.Property<string>("BlockDimensions")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("FanAirFlow")
                        .HasColumnType("text");

                    b.Property<int?>("FanCount")
                        .HasColumnType("integer");

                    b.Property<string>("FanDimensions")
                        .HasColumnType("text");

                    b.Property<string>("FanNoise")
                        .HasColumnType("text");

                    b.Property<string>("FanRpm")
                        .HasColumnType("text");

                    b.Property<string>("FanSize")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LedColor")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pressure")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PumpNoise")
                        .HasColumnType("text");

                    b.Property<string>("PumpSpeed")
                        .HasColumnType("text");

                    b.Property<string>("RadiatorMaterial")
                        .HasColumnType("text");

                    b.Property<string>("RadiatorSize")
                        .HasColumnType("text");

                    b.Property<string>("TubeDimensions")
                        .HasColumnType("text");

                    b.Property<string>("TubeMaterial")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WaterCoolers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CartItem", b =>
                {
                    b.HasOne("DDMdiplom.Models.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("DDMdiplom.Models.Build", b =>
                {
                    b.HasOne("DDMdiplom.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DDMdiplom.Models.BuildItem", b =>
                {
                    b.HasOne("DDMdiplom.Models.Build", "Build")
                        .WithMany("Items")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("DDMdiplom.Models.Order", b =>
                {
                    b.HasOne("DDMdiplom.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DDMdiplom.Models.OrderItem", b =>
                {
                    b.HasOne("DDMdiplom.Models.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DDMdiplom.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DDMdiplom.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DDMdiplom.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDMdiplom.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DDMdiplom.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDMdiplom.Models.Build", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DDMdiplom.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
